config/routes.rb
Rails.application.routes.draw do

  resources :error_logs, only: [:show, :index] do
    resources :user_logs, only: [:show, :index]
  end
  post '/error_logs/handle_js', to: 'error_logs#handle_js'

  resources :user_logs, only: [:show, :index] do
    resources :error_logs, only: [:show, :index]
  end

  resources :vulnerability_storages, only: [:show, :index]

  devise_for :users,
             controllers: {
                 omniauth_callbacks: 'users/omniauth_callbacks',
                 registrations: 'users/registrations'
             }

  get '/auth/failure', to: redirect('/')

  namespace :author do

    resources :site_types

    get 'widgets/all', to: 'widgets#all', as: 'widgets_all'
    resources(:widgets) {resources :widget_categories}

    resources :site_storages do
      resources :site_versions do
        # put 'publish', to: 'site_versions#publish'
        resources(:site_types) {get '', to: 'site_storages#show_version'}
      end
      resources(:site_types) {get '', to: 'site_storages#show'}
      resources :widgets
      get 'users', to: 'users#site_users'
    end

    resources :site_versions do
      resources :site_storages do
        put 'activate', to: 'site_versions#activate'
        put 'deactivate', to: 'site_versions#deactivate'
        put 'deploy', to: 'site_versions#deploy'
      end
    end

    resources :widget_categories do
      get 'widgets', to: 'widgets#index'
      resource :widgets
    end

    resources :users do
      resources :site_storages
      resources :widgets
    end
  end

  namespace :saas do
    get 'ali_express/api_tool/:api', to: '/saas/ali_express#api_tool'
  end

  resources :site_storages, path: 'author/site_storages' do
    resources :vulnerability_storages
  end

  resources :vulnerability_storages, only: [:index]

  put '/fetch_external_widget', to: 'author/widgets#external_fetch'
  post '/external_widgets', to: 'author/widgets#external_widgets'

  get '/readability_content/:url', to: 'author/widgets#readability_content'

  get '/sites/:key/:mode(/:version)', to: 'author/site_storages#show', as: 'version'

  put '/sites/:key', to: 'author/site_storages#update'
  put '/sites/activate/:key/:version', to: 'author/site_versions#activate'
  put '/sites/deactivate/:key/:version', to: 'author/site_versions#deactivate'
  put '/sites/:key/:id/publish', to: 'author/site_versions#publish', as: 'publish'
  put '/sites/:key/:id/deploy', to: 'author/site_versions#deploy', as: 'deploy'


  get '/author', to: 'author/author#index'
  get '/embedly', to: 'public/embedly#show'
  get '/widget/fetch_embedded_content', to: 'author/widgets#fetch_embedded_content'

  root 'author/author#index'

  get '*unmatched_route', to: 'application#raise_not_found'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#  provider               :string
#  uid                    :string
#  role_id                :integer
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  failed_attempts        :integer          default(0), not null
#  unlock_token           :string
#  locked_at              :datetime
#  oauth_token            :string
#  oauth_expires_at       :datetime
#  name                   :string
#  image                  :string
#  last_seen              :datetime
#  item_id                :integer
#  original_email         :string
#

class User < ApplicationRecord

  include Gravtastic
  gravtastic

  TEMP_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
      :trackable, :timeoutable, :omniauthable, :lastseenable,
      omniauth_providers: [
          # :digitalocean,
          :twitter,
          :facebook,
          # :google,
          # :amazon,
          :github,
          :bitbucket,
          :linkedin,
          :aliexpress
      ]

  attr_accessor :oauth_expires_at

  has_and_belongs_to_many :author_site_storages,
      class_name: 'Author::SiteStorage'

  belongs_to :author_item,
      class_name: 'Author::Item',
      dependent: :destroy

  has_many :author_widgets,
      class_name: 'Author::Widget',
      dependent: :destroy

  has_many :author_site_storages,
      class_name: 'Author::SiteStorage',
      dependent: :destroy

  has_many :author_site_versions,
      dependent: :destroy,
      class_name: 'Author::SiteVersion'

  has_many :author_site_storage_widgets,
      class_name: 'Author::SiteStorageWidget',
      dependent: :destroy

  has_many :author_site_types,
      class_name: 'Author::SiteType',
      dependent: :destroy

  has_many :author_widget_categories,
      class_name: 'Author::WidgetCategory',
      dependent: :destroy

  has_many :user_logs,
      class_name: 'UserLog',
      dependent: :destroy

  has_many :error_logs,
      class_name: 'ErrorLog',
      dependent: :destroy,
      through: :user_logs

  has_many :vulnerability_storages,
      class_name: 'VulnerabilityStorage',
      dependent: :destroy,
      through: :author_site_storages

  belongs_to :role

  validates_format_of :email,
      with: TEMP_EMAIL_REGEX,
      on: :update,
      uniqueness: {
          case_sensitive: false
      }

  before_create :update_profile
  before_update :update_profile
  after_create :update_item

  def owner_of
    Author::Item.where(user_id: self.id)
  end

  def update_profile
    self.original_email = self.email.clone
    self.email = "#{self.uid}@#{self.provider}.com" unless self.provider.nil?
  end

  def update_item
    item = Author::Item.create(public: false, visible: true, user_id: self.id)
    self.update(author_item_id: item.id)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap {|user| create_from(auth, user)}
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end

  def self.fetch_data(user)
    all
  end

  def online
    where('last_seen > ?', 5.minutes.ago)
  end

  def self.current
    Thread.current[:user]
  end

  def self.current=(user)
    Thread.current[:user] = user
  end

  def set_default_role
    self.role ||= Role.find_by_name('registered')
  end

  private

  ##
  # @param user [Hash]
  def self.create_from(auth, user)
    user.provider = auth.provider
    user.uid = auth.uid
    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at) unless auth.credentials.expires_at.nil?

    user.name = auth.info.name || user.uid
    user.email = auth.info.email || "#{user.uid}@#{user.provider}.com"
    user.password = Devise.friendly_token[0, 20]

    # assuming the user model has an image
    user.image = auth.info.image

    user.build_author_item(public: false, visible: true, user_id: user)
    user.set_default_role

    user.save!
  end
end

app/controllers/author/users_controller.rb
class Author::UsersController < Author::AuthorController

  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users_all = User.all
    @users = @users_all.paginate(page: params[:page], per_page: 15)
  end

  def site_users
    @storage = Author::SiteStorage.find_by_key(params[:site_storage_id])
    @users_all = @storage.users
    @users = @users_all.paginate(page: params[:page], per_page: 15)
  end

  def show

  end

  def new
    render '/partials/form', locals: {title: 'id'}
  end

  def edit
    render '/partials/form', locals: {title: 'original_email'}
  end

  def update

  end

  def destroy

  end

  private

  def set_user
    @author_user = User.find(params[:id])
  end

end

app/helpers/author/author/git_hub_helper.rb
module Author::Author::GitHubHelper
end

app/helpers/author/author_helper.rb
module Author::AuthorHelper

  def development
    site_type('development')
  end

  def consumption
    site_type('consumption')
  end

  def authoring
    site_type('authorize')
  end

  def test
    site_type('test')
  end

  def action?(action)
    action_name == action
  end

  def new?
    action? 'new'
  end

  def edit?
    action? 'edit'
  end

  def new_url
    send("new_author_#{controller_name.singularize}_path")
  end

  def th(names = [])
    "<tr>#{names.map { |n| "<th scope=\"col\">#{n}</th>" }.join}</tr>".html_safe
  end

  def link_to_icon(url, title, icon, css = '', icon_float = 'none', target =
      nil, method = :get)
    link_to url, title: title, target: target, class: css, method: method do
      concat "<i class=\"fa #{icon} float-#{icon_float}\"></i>".html_safe
      concat title
    end
  end

  def link_to_destroy(item, name, destroy_path = nil, style = '')
    title = controller_name.humanize.singularize.downcase
    link_to (destroy_path.nil? ?
        send("author_#{controller_name.singularize}_path", item) :
        destroy_path),
        class: style,
        method: :delete,
        data: {confirm: "#{t('delete_confirm', item: title, name: name)}"} do
      "<i class=\"fa fa-trash\"></i>#{t('delete', item: nil)}".html_safe
    end
  end

  def link_to_edit(item, edit_path = nil, style = '', method = :get)
    link_to (edit_path.nil? ?
        send("edit_author_#{controller_name.singularize}_path", item) : edit_path),
        title: t('edit'),
        method: method,
        class: style do
          "<i class=\"fa fa-edit\"></i>#{t('edit')}".html_safe
        end
  end

  def render_loop(collection, partial)
    if collection.blank?
      (concat "<p class=\"no-data\">#{t('no_data_in_collection', items: controller_name.gsub(/_controller/, '').titleize.humanize)}</p>".html_safe)
    else
      collection.each_with_index do |item, index|
        concat render partial, item: item, index: index
      end
    end
  end

  def render_title
    content_tag(:div, class: 'title') do
    end unless controller_name == 'author'
  end

  def render_text_field(f, name, disabled = false)
    render_field(:text_field, f, name, disabled)
  end

  def render_text(name, value)
    content_tag(:div, class: 'input-group') do
      concat label_tag name, nil, class: 'input-group-addon text-left'
      concat text_field_tag(name, value, {disabled: true, class: 'form-control'})
    end
  end

  def render_text_area(f, name, disabled = false)
    render_field(:text_area, f, name, disabled)
  end

  def render_field_tag(type, name, value, disabled = false, autofocus = false)
    content_tag(:div, class: 'form-group') do
      concat label_tag name, nil
      concat send(type, name, value,
          disabled: disabled,
          autofocus: autofocus,
          class: 'form-control',
          'aria-describedby': "#{name}-help",
          placeholder: "Enter #{name.to_s.humanize}"
      )
      concat content_tag :small,
          'Encrypted content parsed below',
          id: "#{name}-help",
          class: 'form-text text-muted'
    end
  end

  def render_checkbox(f, name, disabled = false)
    content_tag(:div, class: 'input-group mb-1') do
      concat render_group_field(:check_box, f, name, disabled)
      concat text_field_tag(name, name.to_s.humanize, disabled: true, class: 'form-control')
    end
  end

  def render_radio_button(f, name, value, checked = false, disabled = false)
    content_tag(:div, class: 'field') do
      concat f.radio_button(name, value, {disabled: disabled, checked: checked})
      concat f.label name
    end
  end

  def render_group_field(type, f, name, disabled)
    content_tag(:div, nil, class: 'input-group-prepend') do
      content_tag(:div, nil, class: 'input-group-text') do
        concat f.send(type, name, disabled: disabled)
      end
    end
  end

  def render_number_field(f, name, disabled = false, autofocus = false, css = 'col-xs-6')
    render_field(:number_field, f, name, disabled, autofocus, css)
  end

  def render_collection_field(f, name, opts)
    "<div class=\"input-group mb-1\">
      <div class=\"input-group-prepend\">
        <div class=\"input-group-text\">#{f.label opts[:id], name, class: 'm-0'}</div>
      </div>
      #{f.collection_select(opts[:id], opts[:collection], opts[:index], opts[:value], opts[:html] || {}, {class: 'form-control'})}
    </div>".html_safe unless opts[:collection].nil?
  end

  def render_select_field(f, name, opts)
    "<div class=\"input-group mb-1\">
      <div class=\"input-group-prepend\">
        <div class=\"input-group-text\">#{f.label opts[:id], name, class: 'm-0'}</div>
      </div>
      #{f.select(opts[:id], opts[:collection], opts[:html] || {}, {class: 'form-control'})}
    </div>".html_safe unless opts[:collection].nil?
  end

  def render_submit(title = nil, click = 'this.parentNode.parentNode.querySelector(\'form\').submit()')
    name = action_name === 'edit' ? 'Update' : 'Create'
    title = title || "#{name} #{controller_name.singularize.humanize}"
    button_tag title, class: 'btn btn-warning',
        onclick: click,
        data: {disable_with: "Please wait..."}
  end

  def cancel_button(**args)
    name = args[:name] || t('cancel')
    redirect_url = args[:redirect_url] || send("author_#{controller_name}_path")
    link_to name, redirect_url, title: t('cancel')
  end

  def render_notification(item)
    content_tag(:div, class: 'error_explanation') do
      concat content_tag(:h2, "#{pluralize(item.errors.count, 'error')}: prohibited this item from being saved:")
      concat content_tag(:ul, item.errors.full_messages.collect { |message| "<li>#{message}</ li>" }.join.html_safe)
    end if item.errors.any?
  end

  def render_form
    render partial: "/author/#{controller_name}/form",
        locals: {
            item: instance_variable_get("@author_#{controller_name.singularize}"),
            types: @author_site_types
        }
  end

  private

  def render_field(type, f, name, disabled, autofocus = false, css = '')
    content_tag(:div, class: "input-group #{css}") do
      concat f.label name, class: 'input-group-addon text-left'
      concat f.send(type, name, disabled: disabled, autofocus: autofocus,
          class: 'form-control', placeholder: "Enter #{name.to_s.humanize}")
    end
  end

  def add_new_black_list
    %w(site_versions)
  end

  def edit_user(item)
    email = item.user.email
    email = link_to(email, edit_user_registration_path) if email == current_user.email
    "#{email} (#{item.user.role.name.humanize})".html_safe
  end

  def render_json(content, selector, compressed = true, load = true)
    content_tag(:div, class: 'json-view') do
      concat pretty_print(content, selector, compressed) if load
    end
  end

  def pretty_print(content, selector = '.json-view', compressed)
    javascript_pack_tag('parser', id: 'parser',
        'data-compressed': compressed,
        'data-content': content,
        'data-selector': selector)
  end

  def json_pre(json)
    "<pre><code>#{JSON.pretty_generate(JSON.parse(json))}</code></pre>".html_safe
  end

  def bind_events(selectors = [], force = nil)
    pretty_print = selectors.map { |x| "_print(tr.querySelector('li#{x}>div'));" }
    javascript_tag [
        "function _print(param){",
        "var parsed;try{parsed=JSON.parse(param.innerText)}catch(e){parsed=param.innerText}",
        "$(prettyPrint(parsed)).appendTo($(param).empty());}",
        "var toggleTrace=new Event('click');",
        "var table=document.querySelector('##{controller_name}'),",
        "handlers=table.querySelectorAll('td.nw:first-child');",
        "handlers.forEach(function(handler){",
        "handler.addEventListener('click',function(){",
        "var plus=handler.querySelector('.fa-plus'),",
        "minus=handler.querySelector('.fa-minus'),",
        "tr=handler.parentNode.nextElementSibling;",
        "if(tr.classList.contains('hide')){",
        "tr.classList.remove('hide');",
        "if(plus)plus.classList.add('hide');",
        "if(minus)minus.classList.remove('hide');",
        pretty_print.join,
        '}else{',
        "tr.classList.add('hide');",
        "if(plus)plus.classList.remove('hide');",
        "if(minus)minus.classList.add('hide')",
        '}});});',
        "#{'handlers[0].dispatchEvent(toggleTrace)' unless force.nil? }"
    ].join
  end

  def published(item)
    item.get_published_version.version rescue '?'
  end

  def activated(item)
    item.get_activated_version.version rescue '?'
  end

  def author_variable_get(title)
    instance_variable_get("@author_#{controller_name.singularize}").send(title) ||
        (DateTime.now).strftime('%Y %b %d %I:%M:%S %p')
  end

  private

  def site_type(mode)
    Author::SiteType.where(name: mode).first
  end

end

app/helpers/author/widgets_helper.rb
module Author::WidgetsHelper

  def fetch_external_thumbnail(item)
    " style=\"background-image:url('#{item.external_resource}images/#{item.resource}.png');\"".html_safe if item.is_external?
  end

  def redirect_on_cancel(category)
    category.nil? ?
      author_widgets_path :
      author_widget_category_widgets_path(category)
  end

  def create_in_category_url(category)
    category.nil? ?
      new_author_widgets_path :
      new_author_widget_category_widgets_path(category)
  end
end

app/views/author/site_storages/_category_widgets.html.erb
<div class="panel panel-warning">
    <div class="panel-heading">
        <button type="button" class="pull-left glyphicon glyphicon-minus" data-toggle="collapse" data-target="#toggle-widgets-<%= item.id %>"></button>
        <h3 class="panel-title">
            <span class="pull-left category-title" onclick="selectAll(this)"><%= item.name_value %></span>
            <span class="badge selected" title="<%= t('selected') %>">0</span>/
            <span class="badge" title="<%= t('total') %>"><%= item.author_widgets.length %></span>
        </h3>
    </div>
    <div class="panel-body">
        <div class="site-widgets-wrapper collapse in row" id="toggle-widgets-<%= item.id %>" aria-expanded="true">
            <% render_loop(item.author_widgets.order(:name), 'site_widget') %>
        </div>
    </div>
</div>

app/views/author/site_storages/_footer.html.erb
<div>
  <%= render 'menu', site: site %>
  <%= link_to t('version'), author_site_storage_site_versions_path(site) %><%= ": #{site.get_activated_version.try(:version) || '?'} (#{site.author_site_versions.length})" %>
</div>

app/views/author/site_storages/_form.html.erb
<%= form_for(item) do |f| -%>
  <% content = item.get_activated_version.content rescue nil %>
  <%= render_notification(item) -%>
  <%= render_text_field(f, :key) if new? %>
  <%= render_field_tag(:text_area_tag, :content, content, true) unless new? -%>
  <%= render_json(content, '.json-view') unless content.nil? %>

  <%= render 'author/author/item', f: f -%>

  <div class="container m-0 p-0">
    <div class="row">
      <div class="col">
        <%= render_collection_field(f, t('type'), {
            id: :site_type_id,
            collection: types,
            index: :id,
            value: :name
        }) -%>
      </div>
      <div class="col">
        <%= render_select_field(f, t('layout_type'), {
            id: :layout_type,
            collection: Author::SiteStorage.layout_types.keys
        }) %>
      </div>
      <div class="col">
        <%= render_activated_version(f) -%>
      </div>
    </div>
  </div>
  <div class="card mt-5">
    <div class="card-header">
      <h6 class="card-title mb-0">
        All widgets
        <span class="badge badge-secondary">
          /<%= @author_site_storage.author_widgets.size %>
        </span>
      </h6>
    </div>
    <div class="card-body">
      <%= render 'author/site_storages/widgets/select_widgets' unless new? %>
    </div>
  </div>
<% end -%>

app/views/author/site_storages/_menu.html.erb
<%= link_to_icon(author_site_storage_widgets_path(item),
    t('widgets'),
    'fa-th-large',
    'dropdown-item') %>
<%= link_to_icon(author_site_storage_users_path(item),
    t('users'),
    'fa-user',
    'dropdown-item') %>
<div class="dropdown-divider with-text"><%= t('publish') %></div>
<%= link_to_icon(
        publish_path(item, item.get_activated_version),
        t('publish_activated'),
        'fa-lightbulb',
        'dropdown-item'
    ) unless item.get_activated_version.nil? %>
<%= link_to_icon(publish_path(item, item.get_last_version),
    t('publish_last'),
    'fa-lightbulb',
    'dropdown-item') %>
<div class="dropdown-divider with-text"><%= t('sites_versions') %></div>
<%= link_to_icon(author_site_storage_site_versions_path(item),
    t('sites_all_versions'),
    'fa-code-branch',
    'dropdown-item') %>
<%= link_to_icon(edit_author_site_storage_site_version_path(item, item.get_last_version),
    t('sites_latest_version'),
    'fa-code-branch',
    'dropdown-item') %>
<%= link_to_icon(edit_author_site_storage_site_version_path(item, item.get_activated_version),
    t('sites_activated_version'),
    'fa-code-branch',
    'dropdown-item') unless item.get_activated_version.nil? %>
<%= link_to_icon(edit_author_site_storage_site_version_path(item, item.get_published_version),
    t('sites_published_version'),
    'fa-code-branch',
    'dropdown-item') unless item.get_published_version.nil? %>

app/views/author/site_storages/_published.html.erb
<% style = publish ? 'published' : 'offline' %>
<h5 class="<%= style %>"><%= style %></h5>

app/views/author/site_storages/_show.html.erb
<% key = storage[:key] %>
<%= stylesheet_link_tag 'general', media: 'all' %>
<%= stylesheet_link_tag("public/#{key}/css/general") %>
<%= javascript_include_tag(
        'scripts/core/lib/require',
        'data-resource': key,
        'data-user': current_user.nil? ? 'guest' : current_user.email,
        'data-current': storage[:show],
        'data-published': storage[:published],
        'data-version': storage[:last],
        'data-activated': storage[:activated],
        'data-mode': storage[:mode],
        'data-environment': Rails.env,
        'data-uuid': storage[:uuid],
        'data-main': storage[:mode] == 'consumption' ?
            # javascript_path('target/production') :
            javascript_path('public/development') :
            javascript_path('public/development'),
            # javascript_path("public/#{storage[:mode]}"),
        'id': 'require-init'
    ) %>

<%= javascript_tag defer: 'defer', id: 'preload' do -%>
    (function(){
    window.localStorage['<%= key %>'] = '<%= storage[:content] %>';
    var script = document.getElementById('preload');
    script.parentNode.removeChild(script);
    })();
<% end -%>

app/views/author/site_storages/_show_js.html.erb
<% if @storage[:show].nil? %>
  <p class="undefined-site"><%= t('undefined_version') %></p>
<% elsif @storage[:content].nil? && is_consumption?(@storage[:mode]) %>
  <p class="undefined-site"><%= t('not_published') %></p>
<% else %>
  <!-- Loading content -->
  <%= javascript_tag do -%>
    window.localStorage.setItem('<%= @storage[:key] %>', '<%= @storage[:content] %>');
  <% end %>
  <!-- /Loading content -->
<% end %>

app/views/author/site_storages/_site_widget.html.erb
<div class="site-widgets input-group<%= item.is_external? ? ' external' : '' -%>">
    <%= label_tag dom_id(item),
                  nil, {
                          class: "input-group-addon widget #{item.resource.gsub(/\./, '-')}",
                          title: "#{item.name}\n#{item.description}"
                  } do -%>
        <%= check_box_tag 'author_site_storage[author_site_storage_widget_ids][]',
                          item.id,
                          @author_site_storage.author_widget_ids.include?(item.id), {
                                  id: dom_id(item),
                                  class: 'form-control',
                                  onclick: 'updateCounter(this)'
                          } -%>
        <span><%= item.name %></span>
    <% end %>
</div>

app/views/author/site_storages/_sites.html.erb
<div class="col-sm-6 col-lg-3">
  <% widgets = item.author_site_storage_widgets.length %>
  <% versions = item.author_site_versions.length %>
  <% type = item.author_site_type.name %>
  <%= render 'author/author/ibox_edit',
      item_type: 'edit',
      item_bg: last_published?(item) ? 'bg-green' : 'bg-info',
      item: item,
      item_info: item.key,
      item_title: [
          "#{ibox_text(t('site_connected_widgets'), badge(widgets), widgets)}",
          "#{ibox_text(t('version').pluralize, 'dark', versions)}",
          "#{ibox_text(t('type'), 'dark', type)}"
      ].join.html_safe,
      item_icon: 'fa-globe',
      item_menu: 'menu' %>
</div>

app/views/author/site_storages/index.html.erb
<%= render 'partials/panel_cards', entity: @author_site_storages, type: 'sites' %>

app/views/author/site_storages/show.html.erb
<%= render_as @storage[:layout], @storage, current_user %>