config/routes.rb
Rails.application.routes.draw do

  resources :error_logs, only: [:show, :index] do
    resources :user_logs, only: [:show, :index]
  end
  post '/error_logs/handle_js', to: 'error_logs#handle_js'

  resources :user_logs, only: [:show, :index] do
    resources :error_logs, only: [:show, :index]
  end

  resources :vulnerability_storages, only: [:show, :index]

  devise_for :users,
             controllers: {
                 omniauth_callbacks: 'users/omniauth_callbacks',
                 registrations: 'users/registrations'
             }

  get '/auth/failure', to: redirect('/')

  namespace :author do

    resources :site_types

    get 'widgets/all', to: 'widgets#all', as: 'widgets_all'
    resources(:widgets) {resources :widget_categories}

    resources :site_storages do
      resources :site_versions do
        # put 'publish', to: 'site_versions#publish'
        resources(:site_types) {get '', to: 'site_storages#show_version'}
      end
      resources(:site_types) {get '', to: 'site_storages#show'}
      resources :widgets
      get 'users', to: 'users#site_users'
    end

    resources :site_versions do
      resources :site_storages do
        put 'activate', to: 'site_versions#activate'
        put 'deactivate', to: 'site_versions#deactivate'
        put 'deploy', to: 'site_versions#deploy'
      end
    end

    resources :widget_categories do
      get 'widgets', to: 'widgets#index'
      resource :widgets
    end

    resources :users do
      resources :site_storages
      resources :widgets
    end
  end

  namespace :saas do
    get 'ali_express/api_tool/:api', to: '/saas/ali_express#api_tool'
  end

  resources :site_storages, path: 'author/site_storages' do
    resources :vulnerability_storages
  end

  resources :vulnerability_storages, only: [:index]

  put '/fetch_external_widget', to: 'author/widgets#external_fetch'
  post '/external_widgets', to: 'author/widgets#external_widgets'

  get '/readability_content/:url', to: 'author/widgets#readability_content'

  get '/sites/:key/:mode(/:version)', to: 'author/site_storages#show', as: 'version'

  put '/sites/:key', to: 'author/site_storages#update'
  put '/sites/activate/:key/:version', to: 'author/site_versions#activate'
  put '/sites/deactivate/:key/:version', to: 'author/site_versions#deactivate'
  put '/sites/:key/:id/publish', to: 'author/site_versions#publish', as: 'publish'
  put '/sites/:key/:id/deploy', to: 'author/site_versions#deploy', as: 'deploy'


  get '/author', to: 'author/author#index'
  get '/embedly', to: 'public/embedly#show'
  get '/widget/fetch_embedded_content', to: 'author/widgets#fetch_embedded_content'

  root 'author/author#index'

  get '*unmatched_route', to: 'application#raise_not_found'

end

app/controllers/author/author_controller.rb
class Author::AuthorController < ApplicationController

  before_action :authenticate_user!

  layout 'author'
  # rescue_from CanCan::AccessDenied do |exception|
  #   flash[:error] = exception.message
  #   redirect_to root_url
  # end

  def index
    @author = Author.fetch_data(current_user)
  end

  def respond_with_error(status = :unprocessable_entity)
    respond_to do |format|
      format.html {redirect_to send("author_#{controller_name}_path"), notice: :error}
      format.json {render json: instance_variable_get("@author_#{controller_name.singularize}").errors, status: status}
    end
  end

  def respond_with_xhr(json_response)
    respond_to {|format| format.json {render json: json_response, status: t("success_#{action_name}")}}
  end

  def response_with_json_builder(json_response)
    @json_response = json_response
  end

  def respond_default(url = send("author_#{controller_name}_path"))
    respond_to do |format|
      format.html {redirect_to url, notice: t("success_#{action_name}")}
      format.json {render :index, status: action_name.to_sym, location: instance_variable_get("@author_#{controller_name.singularize}")}
    end
  end

  def render_form(locals)
    render '/partials/form', locals: locals
  end
end

app/controllers/author/users_controller.rb
class Author::UsersController < Author::AuthorController

  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users_all = User.all
    @users = @users_all.paginate(page: params[:page], per_page: 15)
  end

  def site_users
    @storage = Author::SiteStorage.find_by_key(params[:site_storage_id])
    @users_all = @storage.users
    @users = @users_all.paginate(page: params[:page], per_page: 15)
  end

  def show

  end

  def new
    render '/partials/form', locals: {title: 'id'}
  end

  def edit
    render '/partials/form', locals: {title: 'original_email'}
  end

  def update

  end

  def destroy

  end

  private

  def set_user
    @author_user = User.find(params[:id])
  end

end

app/helpers/author/author/git_hub_helper.rb
module Author::Author::GitHubHelper
end

app/helpers/author/author_helper.rb
module Author::AuthorHelper

  def development
    site_type('development')
  end

  def consumption
    site_type('consumption')
  end

  def authoring
    site_type('authorize')
  end

  def test
    site_type('test')
  end

  def action?(action)
    action_name == action
  end

  def new?
    action? 'new'
  end

  def edit?
    action? 'edit'
  end

  def new_url
    send("new_author_#{controller_name.singularize}_path")
  end

  def th(names = [])
    "<tr>#{names.map { |n| "<th scope=\"col\">#{n}</th>" }.join}</tr>".html_safe
  end

  def link_to_icon(url, title, icon, css = '', icon_float = 'none', target =
      nil, method = :get)
    link_to url, title: title, target: target, class: css, method: method do
      concat "<i class=\"fa #{icon} float-#{icon_float}\"></i>".html_safe
      concat title
    end
  end

  def link_to_destroy(item, name, destroy_path = nil, style = '')
    title = controller_name.humanize.singularize.downcase
    link_to (destroy_path.nil? ?
        send("author_#{controller_name.singularize}_path", item) :
        destroy_path),
        class: style,
        method: :delete,
        data: {confirm: "#{t('delete_confirm', item: title, name: name)}"} do
      "<i class=\"fa fa-trash\"></i>#{t('delete', item: nil)}".html_safe
    end
  end

  def link_to_edit(item, edit_path = nil, style = '', method = :get)
    link_to (edit_path.nil? ?
        send("edit_author_#{controller_name.singularize}_path", item) : edit_path),
        title: t('edit'),
        method: method,
        class: style do
          "<i class=\"fa fa-edit\"></i>#{t('edit')}".html_safe
        end
  end

  def render_loop(collection, partial)
    if collection.blank?
      (concat "<p class=\"no-data\">#{t('no_data_in_collection', items: controller_name.gsub(/_controller/, '').titleize.humanize)}</p>".html_safe)
    else
      collection.each_with_index do |item, index|
        concat render partial, item: item, index: index
      end
    end
  end

  def render_title
    content_tag(:div, class: 'title') do
    end unless controller_name == 'author'
  end

  def render_text_field(f, name, disabled = false)
    render_field(:text_field, f, name, disabled)
  end

  def render_text(name, value)
    content_tag(:div, class: 'input-group') do
      concat label_tag name, nil, class: 'input-group-addon text-left'
      concat text_field_tag(name, value, {disabled: true, class: 'form-control'})
    end
  end

  def render_text_area(f, name, disabled = false)
    render_field(:text_area, f, name, disabled)
  end

  def render_field_tag(type, name, value, disabled = false, autofocus = false)
    content_tag(:div, class: 'form-group') do
      concat label_tag name, nil
      concat send(type, name, value,
          disabled: disabled,
          autofocus: autofocus,
          class: 'form-control',
          'aria-describedby': "#{name}-help",
          placeholder: "Enter #{name.to_s.humanize}"
      )
      concat content_tag :small,
          'Encrypted content parsed below',
          id: "#{name}-help",
          class: 'form-text text-muted'
    end
  end

  def render_checkbox(f, name, disabled = false)
    content_tag(:div, class: 'input-group mb-1') do
      concat render_group_field(:check_box, f, name, disabled)
      concat text_field_tag(name, name.to_s.humanize, disabled: true, class: 'form-control')
    end
  end

  def render_radio_button(f, name, value, checked = false, disabled = false)
    content_tag(:div, class: 'field') do
      concat f.radio_button(name, value, {disabled: disabled, checked: checked})
      concat f.label name
    end
  end

  def render_group_field(type, f, name, disabled)
    content_tag(:div, nil, class: 'input-group-prepend') do
      content_tag(:div, nil, class: 'input-group-text') do
        concat f.send(type, name, disabled: disabled)
      end
    end
  end

  def render_number_field(f, name, disabled = false, autofocus = false, css = 'col-xs-6')
    render_field(:number_field, f, name, disabled, autofocus, css)
  end

  def render_collection_field(f, name, opts)
    "<div class=\"input-group mb-1\">
      <div class=\"input-group-prepend\">
        <div class=\"input-group-text\">#{f.label opts[:id], name, class: 'm-0'}</div>
      </div>
      #{f.collection_select(opts[:id], opts[:collection], opts[:index], opts[:value], opts[:html] || {}, {class: 'form-control'})}
    </div>".html_safe unless opts[:collection].nil?
  end

  def render_select_field(f, name, opts)
    "<div class=\"input-group mb-1\">
      <div class=\"input-group-prepend\">
        <div class=\"input-group-text\">#{f.label opts[:id], name, class: 'm-0'}</div>
      </div>
      #{f.select(opts[:id], opts[:collection], opts[:html] || {}, {class: 'form-control'})}
    </div>".html_safe unless opts[:collection].nil?
  end

  def render_submit(title = nil, click = 'this.parentNode.parentNode.querySelector(\'form\').submit()')
    name = action_name === 'edit' ? 'Update' : 'Create'
    title = title || "#{name} #{controller_name.singularize.humanize}"
    button_tag title, class: 'btn btn-warning',
        onclick: click,
        data: {disable_with: "Please wait..."}
  end

  def cancel_button(**args)
    name = args[:name] || t('cancel')
    redirect_url = args[:redirect_url] || send("author_#{controller_name}_path")
    link_to name, redirect_url, title: t('cancel')
  end

  def render_notification(item)
    content_tag(:div, class: 'error_explanation') do
      concat content_tag(:h2, "#{pluralize(item.errors.count, 'error')}: prohibited this item from being saved:")
      concat content_tag(:ul, item.errors.full_messages.collect { |message| "<li>#{message}</ li>" }.join.html_safe)
    end if item.errors.any?
  end

  def render_form
    render partial: "/author/#{controller_name}/form",
        locals: {
            item: instance_variable_get("@author_#{controller_name.singularize}"),
            types: @author_site_types
        }
  end

  private

  def render_field(type, f, name, disabled, autofocus = false, css = '')
    content_tag(:div, class: "input-group #{css}") do
      concat f.label name, class: 'input-group-addon text-left'
      concat f.send(type, name, disabled: disabled, autofocus: autofocus,
          class: 'form-control', placeholder: "Enter #{name.to_s.humanize}")
    end
  end

  def add_new_black_list
    %w(site_versions)
  end

  def edit_user(item)
    email = item.user.email
    email = link_to(email, edit_user_registration_path) if email == current_user.email
    "#{email} (#{item.user.role.name.humanize})".html_safe
  end

  def render_json(content, selector, compressed = true, load = true)
    content_tag(:div, class: 'json-view') do
      concat pretty_print(content, selector, compressed) if load
    end
  end

  def pretty_print(content, selector = '.json-view', compressed)
    javascript_pack_tag('parser', id: 'parser',
        'data-compressed': compressed,
        'data-content': content,
        'data-selector': selector)
  end

  def json_pre(json)
    "<pre><code>#{JSON.pretty_generate(JSON.parse(json))}</code></pre>".html_safe
  end

  def bind_events(selectors = [], force = nil)
    pretty_print = selectors.map { |x| "_print(tr.querySelector('li#{x}>div'));" }
    javascript_tag [
        "function _print(param){",
        "var parsed;try{parsed=JSON.parse(param.innerText)}catch(e){parsed=param.innerText}",
        "$(prettyPrint(parsed)).appendTo($(param).empty());}",
        "var toggleTrace=new Event('click');",
        "var table=document.querySelector('##{controller_name}'),",
        "handlers=table.querySelectorAll('td.nw:first-child');",
        "handlers.forEach(function(handler){",
        "handler.addEventListener('click',function(){",
        "var plus=handler.querySelector('.fa-plus'),",
        "minus=handler.querySelector('.fa-minus'),",
        "tr=handler.parentNode.nextElementSibling;",
        "if(tr.classList.contains('hide')){",
        "tr.classList.remove('hide');",
        "if(plus)plus.classList.add('hide');",
        "if(minus)minus.classList.remove('hide');",
        pretty_print.join,
        '}else{',
        "tr.classList.add('hide');",
        "if(plus)plus.classList.remove('hide');",
        "if(minus)minus.classList.add('hide')",
        '}});});',
        "#{'handlers[0].dispatchEvent(toggleTrace)' unless force.nil? }"
    ].join
  end

  def published(item)
    item.get_published_version.version rescue '?'
  end

  def activated(item)
    item.get_activated_version.version rescue '?'
  end

  def author_variable_get(title)
    instance_variable_get("@author_#{controller_name.singularize}").send(title) ||
        (DateTime.now).strftime('%Y %b %d %I:%M:%S %p')
  end

  private

  def site_type(mode)
    Author::SiteType.where(name: mode).first
  end

end

app/helpers/author/site_storages_helper.rb
module Author::SiteStoragesHelper

  def render_activated_version(f)
    render_collection_field(f, 'Version', {
        id: :activated_version,
        collection: @versions[:all],
        index: :id,
        value: :version,
        html: {
            selected: @versions[:activated].nil? ?
                nil : @versions[:activated].id
        }
    }) if @versions[:all].length > 0 if action_name == 'edit'
  end

  def creator?(user, creator)
    user.id == creator.id
  end

  def user_th
    th(%w(Email Name Provider Online Signin))
  end

  def user_td(user, creator)
    [
        "<tr#{creator?(user, creator) ? ' class="success"' : ''}>",
        "<td>#{link_to user.email}</td>",
        "<td>#{user.name}</td>",
        "<td>#{user.provider || t('password')}</td>",
        "<td><i class=\"glyphicon#{user.last_seen > 5.minutes.ago ? ' glyphicon-eye-open' : ''}\"</i></td>",
        "<td class=\"nw c\">#{user.last_sign_in_at.strftime('%Y %b %d %I:%M:%S %p')}</td></tr>"
    ].join.html_safe
  end

  def widget_selected?(item)
    @author_site_storage.author_widget_ids.include?(item.id)
  end

  def last_published?(item)
    av = activated(item)
    pv = published(item)
    av == pv && (av != '?' || pv != '?')
  end

  def render_as(layout = 'js', collection, user)
    render "show_#{layout}", storage: collection, current_user: user
  end

  def widget_css_class(item)
    selected = widget_selected?(item) ? ' selected' : ''
    "input-group-addon widget #{item.resource.gsub(/\./, '-')}#{selected}"
  end

  def external_widget(item)
    item.is_external? ? ' external' : ''
  end

end

app/helpers/author/site_versions_helper.rb
module Author::SiteVersionsHelper

  def version_th
    th(%w(Version Type Site Owner Date))
  end

  def version_td(collection)
    collection.first.map { |site_version| [
        "<tr#{site_version.activated ? ' class="success"' : ''}>",
        "<td class=\"separate\">#{site_menu(site_version)}#{site_version.version}</td>",
        version_type(site_version),
        "<td>#{link_to site_version.author_site_storage.key, edit_author_site_storage_path(site_version.author_site_storage)}</td>",
        "<td>#{site_version.author_item.user.original_email}</td>",
        "<td>#{site_version.author_item.created_at.strftime('%Y %b %d %I:%M:%S %p')}</td>",
        '</tr>'
    ] unless site_version.nil? }.join.html_safe
  end

  def version_type(version)
    text = []
    text.push('Published') if version.published
    text.push('Activated') if version.activated
    text.push('Deployed') if version.deployed
    text.push('Latest') if version == @partial[:latest]
    text.push('Draft') if text.empty?
    "<td>#{text.join('/')}</td>"
  end

  def site_menu(site_version)
    render 'author/site_versions/site_menu', item: site_version
  end

  def activation_link(item)
    send("author_site_version_site_storage_#{item.activated? ? 'de' : ''}activate_path", item, item.author_site_storage)
  end

  def activation_name(item)
    t("site_version_#{item.activated? ? 'de' : ''}activate")
  end

  def activation_icon(item)
    "fa-thumbs-#{item.activated? ? 'down' : 'up'}"
  end

  def get_version_style(item, latest)
    style = 'secondary'
    style = 'warning' if latest == item
    style = 'success' if item.published
    style = 'info' if item.activated
    style
  end

end

app/helpers/author/widgets_helper.rb
module Author::WidgetsHelper

  def fetch_external_thumbnail(item)
    " style=\"background-image:url('#{item.external_resource}images/#{item.resource}.png');\"".html_safe if item.is_external?
  end

  def redirect_on_cancel(category)
    category.nil? ?
      author_widgets_path :
      author_widget_category_widgets_path(category)
  end

  def create_in_category_url(category)
    category.nil? ?
      new_author_widgets_path :
      new_author_widget_category_widgets_path(category)
  end
end

app/views/author/widgets/_all_widgets.html.erb
<%= render 'partials/panel_cards', entity: @partial[:collection], type: 'category_widgets' %>

app/views/author/widgets/_categories.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
      <%= controller_name.humanize %>
      <span class="badge badge-secondary"><%= @json_data[:widgets_all].length %></span>
    </h3>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-lg-3 col-sm-6 col-xs-12">
        <% widgets = @json_data[:widgets_all].length || 0 %>
        <%= render 'author/author/ibox_index',
            item_bg: 'bg-green',
            item_path: '/author/widgets/all',
            item_title: "#{t('widgets')} <span class=\"badge
      badge-#{badge(widgets)}\">#{widgets}</span>".html_safe,
            item_info: t('all'),
            item_icon: 'fa-th-large' %>
      </div>
      <% render_loop(@json_data[:site_widgets], 'site_widgets') %>
    </div>
  </div>
</div>

app/views/author/widgets/_category_widgets.html.erb
<div class="panel panel-warning">
  <div class="panel-heading">
    <button type="button"
            class="pull-left glyphicon glyphicon-minus"
            data-toggle="collapse"
            data-target="#toggle-widgets-<%= item[:category].id %>"></button>
    <h3 class="panel-title">
      <span class="pull-left category-title">
        <%= item[:category].name_value %>
      </span>
      <span class="badge"><%= item[:widgets].length %></span>
    </h3>
  </div>
  <div class="panel-body">
    <div class="collapse in row"
         id="toggle-widgets-<%= item[:category].id %>"
         aria-expanded="true">
      <% unless @category.nil? %>
          <div class="col-lg-3 col-sm-6 col-xs-12">
            <%= render 'author/author/ibox_new', url: create_in_category_url(@category) %>
          </div>
      <% end %>
      <% render_loop(item[:widgets], 'widget') %>
    </div>
  </div>
  <div class="panel-footer m-20">
    <%= cancel_button(name: t('back')) -%>
  </div>
</div>

app/views/author/widgets/_form.html.erb
<%= form_for(item) do |f| %>
    <%= render_notification(item) %>
    <div class="input-group ">
      <label class="input-group-addon text-left"><%= t('category') %></label>
      <input class="form-control" type="text" disabled="disabled"
             value="<%= @category.name_value %>"/>
    </div>
    <%= render_text_field(f, :resource, is_edit?) %>
    <%= render_text_field(f, :name) %>
    <%= render_text_area(f, :description) %>
    <%= render_text_area(f, :thumbnail) %>
    <%= image_tag item.thumbnail unless item.thumbnail.nil? %>
    <%= render_number_field(f, :width, false, false, 'pull-left col-xs-6') %>
    <%= render_number_field(f, :height) %>
    <div class="panel-footer m-20">
      <%= cancel_button(redirect_url: redirect_on_cancel(@category)) -%>
      <%= render_submit(f) -%>
    </div>
<% end %>
<%= javascript_tag do %>
    $('#author_widget_thumbnail').on('change', function(e){$('.edit_author_widget > img').attr('src', e.target.value);});
<% end %>

app/views/author/widgets/_site_widgets.html.erb
<div class="col-lg-3 col-sm-6 col-xs-12">
  <% widgets = item[:widgets].length || 0 %>
  <%= render 'author/author/ibox_index',
      item_bg: 'bg-yellow',
      item_path: author_widget_category_widgets_path(item[:category]),
      item_title: "#{t('widgets')} <span class=\"badge
      badge-#{badge(widgets)}\">#{widgets}</span>".html_safe,
      item_info: item[:category].name_value,
      item_icon: 'fa-th-large' %>
</div>

app/views/author/widgets/_widget.html.erb
<div class="col-lg-3 col-sm-6 col-xs-12">
  <div class="small-box bg-gray">
    <div class="inner">
      <h2 title="<%= item.name %>"><%= item.name %></h2>
      <p title="<%= item.description %>"><%= item.description %></p>
      <span><%= item.width %> x <%= item.height %></span>
    </div>
    <div class="widget <%= item.resource.gsub(/\./, '-') %>"<%= fetch_external_thumbnail(item) %>></div>
    <div class="btn-group btn-group-xs small-box-footer animated fadeIn clearfix" role="group" aria-label="Extra-small button group">
      <%= link_to_edit(item, nil, 'btn btn-primary') %>
      <%= link_to_destroy(item, item.name) %>
    </div>
  </div>
</div>

app/views/author/widgets/index.html.erb
<%= render @partial[:name] %>

app/views/author/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author_widget.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @author_widget.description %>
</p>

<p>
  <strong>Thumbnail:</strong>
  <%= @author_widget.thumbnail %>
</p>

<p>
  <strong>Width:</strong>
  <%= @author_widget.width %>
</p>

<p>
  <strong>Height:</strong>
  <%= @author_widget.height %>
</p>

<p>
  <strong>Category:</strong>
  <%= @author_widget.author_widget_category.name_value %>
</p>

<p>
  <strong>Resource:</strong>
  <%= @author_widget.resource %>
</p>

<%= link_to 'Edit', edit_author_widget_path(@author_widget) %> |
<%= link_to 'Back', author_widgets_path %>